// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxIUCej8he4Snm8vR1adZXG8HNG8-ONeo',
    appId: '1:455732782494:web:be52861b00e49fc88e228f',
    messagingSenderId: '455732782494',
    projectId: 'connect-9037e',
    authDomain: 'connect-9037e.firebaseapp.com',
    storageBucket: 'connect-9037e.appspot.com',
    measurementId: 'G-Y49PYWZ8SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhG9CsJdIcUtDH_95bB_aIwZSJ1n4N1p0',
    appId: '1:455732782494:android:e6ee06e1086388d38e228f',
    messagingSenderId: '455732782494',
    projectId: 'connect-9037e',
    storageBucket: 'connect-9037e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0IlJ_zAKPKIi1nOfNnzXSzoWLuWXJjtw',
    appId: '1:455732782494:ios:5f5a69908d0b54318e228f',
    messagingSenderId: '455732782494',
    projectId: 'connect-9037e',
    storageBucket: 'connect-9037e.appspot.com',
    iosBundleId: 'com.example.connectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0IlJ_zAKPKIi1nOfNnzXSzoWLuWXJjtw',
    appId: '1:455732782494:ios:e2d561bc43ca8fff8e228f',
    messagingSenderId: '455732782494',
    projectId: 'connect-9037e',
    storageBucket: 'connect-9037e.appspot.com',
    iosBundleId: 'com.example.connectApp.RunnerTests',
  );
}
